language: node_js
node_js:
- stable
after_success: npm run coverage && ./tools/merge-development-with-master.sh
sudo: false
deploy:
  provider: heroku
  app: boo-kings
  on: master
  run:
  - nf start
  api_key:
    secure: QySWI6oSZJHrOuXnwHf//Jrh5vDb52kkwc0wDgfSZzVLqyQPpyqjwDrPXhSpOpJOi2ItvFPaO/g+1aAYzQDTMawTiLLRe/mMRI1nXzJ6E57hVGpGZOKbsk4+HvxB8j/M1POFKvluorczZOTvt9+cKv6I8njlXiKDbYM1pz8J+C8LwHPgk/ne/E4nMgCwQtfhQFIHcKb5c3eUcGd2O/bFzm44buWIblX6EuZjpIOvmX6p821Xc9WPggLwOH07cUbBvMlSEs2aM0jZwPvCcTTPMDu6tehTH2hE0vMNPOD16LconESZGxhM6bSuNw0S/twL1FHF/tNgeUEBM+uVk2g48b2Ye9quj7cSQVRFbGz+8Jc9qtWX4QXyGuXrV2SpowVAdyKlVCp3vSbkvC1c0xoxOSRqo65+XCUJUtrFurxk8LAxlNST5B2hBeWSg30RSmiR474EQothx4MlFIatTs+NUlsuxMesjQOrBODl0cVj7EajwokRGsJ8WFLnuzWbFnsFxmvo3p6xlE425Dm2vLiJuHtoIf6FaxFMTXVLkKD+JmQ79liFuGweGK0TuVH6L6KqC6GRsPOIo14fUOb95FnLMbR26PBlYwesp6MOmQpffHZnL3fvOgzIgYLMkweiKrOlY8VxjngzDz9h6Mz9i5pPi7KYxN7/HqnDID7jG/d6mDc=
