language: node_js
node_js:
- stable
sudo: false
deploy:
  provider: heroku
  app: boo-kings
  on: master
  run:
  - nf start
  api_key:
    secure: Rv8Q9s0xknqfvw1xjL+dEGWj0N/zks+/HjgaiMkcGdoOi/AztQnZV5nA9WdBSe/6Nvm4pGyb0ioZMHGGaN1nHOqHsaIS6JsmhzKneGyMH/qJUbjZ//bgeWXi/gGcW0YmSfk+KI2MDRiWYZAfmIoHOUBnxXNswZ5rMa3AywMvvQsry9uQ4YFUtI9es1NonjK82jOXHRR5fwjT7NneUsKMSvgcUdv4E0e3nr9etbwJXW/D8QvEbVlmYrZfK7XYswf7mFLheqg0SbTp2MugXmmxbo9OJQXet5Nz4flGDJlXX+RttuVZ9izWxMgfdVywUJY5jfKe7dF1P4qQNnMx1t3GwEgVyET5kvJygvnXwHPEUKuj49BI4smMzlNSrmfehk6Cn2AbNCUl49tXMGt5LAQCX23aOJIqLb1sYEuAYtXSdNzg8QjJBjSPhao9EFlMg24sfL6rU6IUbYK816VqcPqlble2lcyGXSq4kxC3q2Mzk6fqsyM2gnykbvypRCVoAbJPeByiif2IWVbvrWkgRMO50OcqBqcJp1jiViFeEauXwrVk/0ydmyNikOmkZ4rz7bg1aH9tHZoFQSOmMs3HWtN77o6a7D3jn/fpFglR8QKXHvWhrNEaMrNgqVgGPOvuV5qGrwFgSnAL6vA6V/yWMB8rBZ74PQX3Q+RD17BRZiueY0A=
