version: "3"
services:
  web:
    image: bookings
    build: .
    volumes:
          - .:/usr/src/app
    ports:
      - "49160:8080"
    links:
      - mongo
    env_file:
      .env
  mongo:
    image: mongo
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - "27017:27017"