version: "3"
services:
  bookings:
    image: bookings
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
          - ../:/usr/src/app
    ports:
      - "49160:8080"
    links:
      - mongo
    env_file:
      ../.env
    environment:
      - MONGODB_URI=mongodb://mongo/bookings
  mongo:
    image: mongo
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - "27017:27017"